stages:
    - test
    - build
    - deploy
  
variables:
    REGISTRY_HOST: gcr.io
    KUBE_DEPLOYMENT: $CI_PROJECT_NAME
    KUBE_ZONE: asia-southeast1-b
    NAMESPACE: $GCP_PROJECT_NAME $CI_COMMIT_REF_NAME
    KUBE_CONTAINER: $CI_PROJECT_NAME-sha256-1
    GIT_DEPTH: 2
    DOCKER_TLS_CERTDIR: ""
    COMPANY_REGISTER_CONSUMER: company-register-consumer
    EMPLOYEE_REGISTER_CONSUMER: employee-register-consumer
    FOLLOW_CONSUMER: follow-consumer
    PMS_CONSUMER: pms-consumer
    KUBE_COMPANY_REGISTER_CONSUMER_CONTAINER: company-register-consumer-sha256-1
    KUBE_EMPLOYEE_REGISTER_CONSUMER_CONTAINER: employee-register-consumer-sha256-1
    KUBE_FOLLOW_CONSUMER_CONTAINER: follow-consumer-sha256-1
    KUBE_PMS_CONSUMER_CONTAINER: pms-consumer-sha256-1
before_script:
    - echo "GCP_ProjectID $GCP_PROJECT_ID"
    - echo "ProjectName   $CI_PROJECT_NAME"
    - echo "Branch        $CI_COMMIT_REF_NAME"
    - echo "Commit        $CI_COMMIT_SHA"
    - echo "Release image $DEPLOY_TARGET"
  
test:
    stage: test
    image: node:latest
    before_script:
      - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
      - cd gitlab.com/$CI_PROJECT_NAMESPACE
      - ln -s $CI_PROJECT_DIR
      - cd $CI_PROJECT_NAME
    script:
      - npm test
    artifacts:
      expire_in: 1 week
      paths:
        - package.json
        - package-lock.json
        - config/
        - app.js
  
  
.build-template: &build-template
    stage: build
    image: docker:18.09.8
    services:
      - docker:18.09.8-dind
    before_script:
      - export DOCKER_HOST="tcp://docker:2375"  
      - echo $GCLOUD_SA_JSON > ${HOME}/key.json
      - docker login -u _json_key --password-stdin https://$REGISTRY_HOST < ${HOME}/key.json
    script:
      - export ENCODED_CONFIG=`echo "$CONFIG" | base64 | tr -d '\n'`
      - echo "-----BEGIN CERTIFICATE-----"$'\n'$DOMAIN_CRT$'\n'"-----END CERTIFICATE-----" > "./crt.pem"
      - echo "-----BEGIN PRIVATE KEY-----"$'\n'$DOMAIN_KEY$'\n'"-----END PRIVATE KEY-----" > "./key.pem"
      - export DOCKER_OPTS="--dns=8.8.8.8 --dns=8.8.4.4"
      - docker build -f $DOCKER_FILE -t $DOCKER_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA -t $DOCKER_IMAGE:$CI_COMMIT_REF_NAME-latest -t $DOCKER_IMAGE:latest --build-arg env=$CI_COMMIT_REF_NAME --build-arg version=$CI_COMMIT_SHA --build-arg config=$ENCODED_CONFIG .
      - docker push $DOCKER_IMAGE
    artifacts:
    after_script:
      - docker logout $REGISTRY_HOST

.build-company-register-consumer-template: &build-company-register-consumer-template
    stage: build
    image: docker:18.09.8
    services:
      - docker:18.09.8-dind
    before_script:
      - export DOCKER_HOST="tcp://docker:2375"
      - echo $GCLOUD_SA_JSON > ${HOME}/key.json
      - docker login -u _json_key --password-stdin https://$REGISTRY_HOST < ${HOME}/key.json
    script:
      - export ENCODED_CONFIG=`echo "$CONFIG" | base64 | tr -d '\n'`
      - echo "-----BEGIN CERTIFICATE-----"$'\n'$DOMAIN_CRT$'\n'"-----END CERTIFICATE-----" > "./crt.pem"
      - echo "-----BEGIN PRIVATE KEY-----"$'\n'$DOMAIN_KEY$'\n'"-----END PRIVATE KEY-----" > "./key.pem"
      - export DOCKER_OPTS="--dns=8.8.8.8 --dns=8.8.4.4"
      - docker build -f $DOCKER_FILE -t $DOCKER_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA -t $DOCKER_IMAGE:$CI_COMMIT_REF_NAME-latest -t $DOCKER_IMAGE:latest --build-arg env=$CI_COMMIT_REF_NAME --build-arg version=$CI_COMMIT_SHA --build-arg config=$ENCODED_CONFIG .
      - docker push $DOCKER_IMAGE
    artifacts:
    after_script:
      - docker logout $REGISTRY_HOST
  
.deploy-template: &deploy-template
    stage: deploy
    image: google/cloud-sdk:latest
    dependencies: []
    script:
      - echo $GCLOUD_SA_JSON > ${HOME}/key.json
      - gcloud auth activate-service-account --key-file ${HOME}/key.json
      - gcloud container clusters get-credentials $KUBE_CLUSTER --zone $KUBE_ZONE --project $GCP_PROJECT_ID
      - kubectl set image -n $NAMESPACE deployment $KUBE_DEPLOYMENT $KUBE_CONTAINER=$DEPLOY_TARGET


      
docker-stg:
    <<: *build-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      DOCKER_IMAGE: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$CI_PROJECT_NAME
      GIT_STRATEGY: none
      DOCKER_FILE: ./main_docker_file
    only:
      - stg

docker-company-register-consumer-stg:
    <<: *build-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      DOCKER_IMAGE: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$COMPANY_REGISTER_CONSUMER
      GIT_STRATEGY: none
      DOCKER_FILE: ./company_register_docker_file
    only:
      - stg

docker-employee-register-consumer-stg:
    <<: *build-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      DOCKER_IMAGE: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$EMPLOYEE_REGISTER_CONSUMER
      GIT_STRATEGY: none
      DOCKER_FILE: ./employee_register_docker_file
    only:
      - stg

docker-follow-consumer-stg:
    <<: *build-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      DOCKER_IMAGE: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$FOLLOW_CONSUMER
      GIT_STRATEGY: none
      DOCKER_FILE: ./follow_docker_file
    only:
      - stg

docker-pms-consumer-stg:
    <<: *build-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      DOCKER_IMAGE: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$PMS_CONSUMER
      GIT_STRATEGY: none
      DOCKER_FILE: ./pms_docker_file
    only:
      - stg

deploy-stg:
    <<: *deploy-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      KUBE_CLUSTER: $KUBE_CLUSTER_STG
      DEPLOY_TARGET: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
      GIT_STRATEGY: none
    only:
      - stg

deploy-company-register-consumer-stg:
    <<: *deploy-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      KUBE_CLUSTER: $KUBE_CLUSTER_STG
      DEPLOY_TARGET: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$COMPANY_REGISTER_CONSUMER:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
      GIT_STRATEGY: none
      KUBE_CONTAINER: $KUBE_COMPANY_REGISTER_CONSUMER_CONTAINER
      KUBE_DEPLOYMENT: $COMPANY_REGISTER_CONSUMER

deploy-employee-register-consumer-stg:
    <<: *deploy-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      KUBE_CLUSTER: $KUBE_CLUSTER_STG
      DEPLOY_TARGET: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$EMPLOYEE_REGISTER_CONSUMER:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
      GIT_STRATEGY: none
      KUBE_CONTAINER: $KUBE_EMPLOYEE_REGISTER_CONSUMER_CONTAINER
      KUBE_DEPLOYMENT: $EMPLOYEE_REGISTER_CONSUMER


deploy-follow-consumer-stg:
    <<: *deploy-template
    variables:
      GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
      GCLOUD_SA_JSON: $GCLOUD_SA_JSON
      KUBE_CLUSTER: $KUBE_CLUSTER_STG
      DEPLOY_TARGET: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$FOLLOW_CONSUMER:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
      GIT_STRATEGY: none
      KUBE_CONTAINER: $KUBE_FOLLOW_CONSUMER_CONTAINER
      KUBE_DEPLOYMENT: $FOLLOW_CONSUMER

deploy-pms-consumer-stg:
  <<: *deploy-template
  variables:
    GCP_PROJECT_ID: $GCP_PROJECT_ID_STG
    GCLOUD_SA_JSON: $GCLOUD_SA_JSON
    KUBE_CLUSTER: $KUBE_CLUSTER_STG
    DEPLOY_TARGET: $REGISTRY_HOST/$GCP_PROJECT_ID_STG/$GCP_PROJECT_NAME/$PMS_CONSUMER:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
    GIT_STRATEGY: none
    KUBE_CONTAINER: $KUBE_PMS_CONSUMER_CONTAINER
    KUBE_DEPLOYMENT: $PMS_CONSUMER